GET http://localhost:4005/auth/users
###

DELETE http://localhost:4005/auth/users/delete

###
POST http://localhost:4005/auth/register
Content-Type: application/json

{
    "email": "test@test",
    "password": "wompwomp"
}

###
POST http://localhost:4005/auth/login
Content-Type: application/json

{
    "email": "fourth@re.doc",
    "password": "hiw"
}